version: '3.8'
services:
  quiz-pro-front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8088:3000"
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
      - ./front/data:/app/data
    restart: always
    environment:
      - VITE_API_BASE_URL=http://your_server_ip:3000